apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true

  - name: MLflow_DB
    type: frser-sqlite-datasource
    access: proxy
    editable: true
    jsonData:
      path: /opt/mlflow.db