{
 "title": "Docker Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Contador de Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{id=~\"/docker/.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Escrita em disco",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{id=~\"/docker/.*\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Uso de Memória RAM",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\"/docker/.*\"} / 1024 / 1024",
     "legendFormat": "Container: {{id}}"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=~\"/docker/.*\"}[5m]) * 100",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}